// <auto-generated />
using KT_31_23_Grigorev_Serafim.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KT_31_23_Grigorev_Serafim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("c_discipline_id")
                        .HasComment("Идентификатор дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bool")
                        .HasColumnName("c_discipline_is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_discipline_name")
                        .HasComment("Название дисциплины");

                    b.HasKey("DisciplineId")
                        .HasName("pk_cd_discipline_discipline_id");

                    b.ToTable("cd_discipline", (string)null);
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("c_grade_id")
                        .HasComment("Идентификатор оценки");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("int4")
                        .HasColumnName("c_grade_value")
                        .HasComment("Значение оценки");

                    b.HasKey("GradeId")
                        .HasName("pk_cd_grade_grade_id");

                    b.HasIndex(new[] { "DisciplineId" }, "idx_cd_grade_fk_f_discipline_id");

                    b.HasIndex(new[] { "StudentId" }, "idx_cd_grade_fk_f_student_id");

                    b.ToTable("cd_grade", (string)null);
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("c_group_id")
                        .HasComment("Идентификатор группы");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Course")
                        .HasColumnType("int4")
                        .HasColumnName("c_group_course")
                        .HasComment("Номер курса");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bool")
                        .HasColumnName("c_group_is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_group_name")
                        .HasComment("Название группы");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId")
                        .HasName("pk_cd_group_group_id");

                    b.HasIndex(new[] { "SpecialtyId" }, "idx_cd_group_fk_f_specialty_id");

                    b.ToTable("cd_group", (string)null);
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("c_specialty_id")
                        .HasComment("Идентификатор специальности");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("c_specialty_code")
                        .HasComment("Код специальности");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_specialty_title")
                        .HasComment("Название специальности");

                    b.HasKey("SpecialtyId")
                        .HasName("pk_cd_specialty_specialty_id");

                    b.ToTable("cd_specialty", (string)null);
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("c_student_id")
                        .HasComment("Идентификатор записи студента");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_firstname")
                        .HasComment("Имя студента");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bool")
                        .HasColumnName("c_student_is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_lastname")
                        .HasComment("Фамилия студента");

                    b.HasKey("StudentId")
                        .HasName("pk_cd_student_student_id");

                    b.HasIndex(new[] { "GroupId" }, "idx_cd_student_fk_f_group_id");

                    b.ToTable("cd_student", (string)null);
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Grade", b =>
                {
                    b.HasOne("KT_31_23_Grigorev_Serafim.Models.Discipline", "Discipline")
                        .WithMany("Grades")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_discipline_id");

                    b.HasOne("KT_31_23_Grigorev_Serafim.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_student_id");

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Group", b =>
                {
                    b.HasOne("KT_31_23_Grigorev_Serafim.Models.Specialty", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_specialty_id");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Student", b =>
                {
                    b.HasOne("KT_31_23_Grigorev_Serafim.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Discipline", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Specialty", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("KT_31_23_Grigorev_Serafim.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
